# Site settings
title: Ignasi Ribó
email: mail@ignasiribo.com
description: Personal page of Ignasi Ribó, Catalan author and scholar.
##baseurl:  # the subpath of your site, e.g. /blog/
url:  http://www.ignasiribo.com
twitter_username: seliestel
github_username:  seliestel

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  books:
    output: true
    permalink: /books/:path/
