# Site settings
title: Ignasi Ribó
email: iribolabastida@gmail.com
description: Personal page of Ignasi Ribó, Catalan author and scholar.
baseurl:  # the subpath of your site, e.g. /blog/
url:  http://www.ignasiribo.com
twitter_username: seliestel
github_username:  seliestel

# Build settings
markdown: kramdown
# highlighter: rouge

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"
# gems: [jekyll-paginate]

collections:
  books:
    output: true
    permalink: /books/:path/



