title: Personal page
author: Ignasi Ribo
email: iribolabastida@gmail.com
description: Personal page.
twitter_username: seliestel
github_username:  seliestel

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
##exclude:
  ##- Gemfile
  ##- Gemfile.lock






# Site settings
##title: Ignasi Ribó
##email: iribolabastida@gmail.com
##description: Personal page of Ignasi Ribó, Catalan author and scholar.
##baseurl:  # the subpath of your site, e.g. /blog/
##url:  http://www.ignasiribo.com
##twitter_username: seliestel
##github_username:  seliestel

# Build settings
##markdown: kramdown
##highlighter: rouge

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"
# gems: [jekyll-paginate]

##collections:
  ##books:
    ##output: true
    ##permalink: /books/:path/



