title: Personal page
author: Ignasi Ribo
email: iribolabastida@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Personal page.
twitter_username: seliestel
github_username:  seliestel

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
##minima:
  ##date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock






# Site settings
##title: Ignasi Ribó
##email: iribolabastida@gmail.com
##description: Personal page of Ignasi Ribó, Catalan author and scholar.
##baseurl:  # the subpath of your site, e.g. /blog/
##url:  http://www.ignasiribo.com
##twitter_username: seliestel
##github_username:  seliestel

# New settings
##github: [metadata]
##encoding: UTF-8
##kramdown:
  ##input: GFM
  ##hard_wrap: false
##future: true
##jailed: false
##theme: jekyll-theme-primer
##gfm_quirks: paragraph_end

# Build settings
##markdown: kramdown
##highlighter: rouge

# Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"
# gems: [jekyll-paginate]

##collections:
  ##books:
    ##output: true
    ##permalink: /books/:path/



